[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["echo 'Static site - no dependencies to install'"]

[phases.build]
cmds = ["echo 'Static site - no build needed'"]

[start]
cmd = "npx serve . -p $PORT"
