[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "chmod +x node_modules/.bin/prisma || true",
  "node node_modules/.bin/prisma generate",
  "npx tsc"
]

[start]
cmd = "npm start"
