
services:
  - type: web
    name: iraq-election-backend
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false

  - type: web
    name: iraq-election-frontend
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: "dist"
    envVars:
      - key: VITE_API_URL
        sync: false
      - key: GENAI_API_KEY
        sync: false
